### ISSUE TITLE
What License?🛎

### ISSUE THREAD

**Issue by grubino** [JoeScho/oas2joi#14]
**Is your feature request related to a problem? Please describe.**
There is no license listed.

**Describe the solution you'd like**
Adding a license.

**Describe alternatives you've considered**
Not adding a license?

**Additional context**
N/A

**Comment by JoeScho** [comment]
Nice - thanks for pointing this out!

**Comment by JoeScho** [comment]
Hey :) This is currently under the MIT licence https://github.com/JoeScho/oas2joi/blob/master/.github/LICENSE
