### ISSUE TITLE
🛎Support for $ref as a file path

### ISSUE THREAD

**Issue by JoeScho** [JoeScho/oas2joi#9]
**Is your feature request related to a problem? Please describe.**
$ref can be a file path, i.e.
```yml
responses:
  '200':
    $ref: '../components/responses/myResponse.yml'
```
Which would break the current implementation (as it would search for the component `myResponse.yml` within the current document.

**Describe the solution you'd like**
Work the same with external files as it does for components in the same file

**Comment by iudex-** [comment]
This and all `$ref` related issues could potentially be solved by using [swagger-parsers `dereference` function](https://github.com/APIDevTools/swagger-parser/blob/master/docs/swagger-parser.md#dereferenceapi-options-callback)

**Comment by JoeScho** [comment]
Nice! Looks like that might do the trick. I don't have much time to fix this at the moment so if you would like to try it out and open a PR then please do :)

**Comment by iudex-** [comment]
I would add it, but i don't see how it would work without changing the signature of the currently exported function.

As the `dereference` function is asynchronous the [exported function](https://github.com/JoeScho/oas2joi/blob/master/index.js#L14) would need to be too...
